### ISSUE TITLE
-nd/--no-404-documentation flag not working

### ISSUE THREAD

**Issue by eirikrye** [timothycrosley/hug#115]
Traceback:
`Traceback (most recent call last):
  File "/home/rye/.virtualenvs/hug/bin/hug", line 11, in <module>
    sys.exit(run.terminal())
  File "/home/rye/.virtualenvs/hug/lib/python3.5/site-packages/hug/run.py", line 171, in terminal
    **server_arguments)
TypeError: server() got an unexpected keyword argument 'sink'`

Tested on a very basic Hug-app with only a single get-handler.

**Comment by timothycrosley** [comment]
Hi @eirikrye,

Thanks for reporting this issue. A fix was just patched and pushed to PYPI in release `1.9.7`.

Thanks!

~Timothy
