### ISSUE TITLE
python3.2 package falcon/request.py invalid syntax problem

### ISSUE THREAD

**Issue by fbukevin** [timothycrosley/hug#121]
My Ubuntu is 14.04 and I just  install the latest Python version and setup_tools.

I install hug with `sudo pip3 install hug --upgrade` successfully. But When I try to import hug in REPL, I got such error:

```
Python 3.2.3 (default, Jun 18 2015, 21:46:42)
[GCC 4.6.3] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import hug
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.2/dist-packages/hug/__init__.py", line 32, in <module>
    from hug import (authentication, directives, documentation, exceptions, format,
  File "/usr/local/lib/python3.2/dist-packages/hug/authentication.py", line 25, in <module>
    from falcon import HTTPUnauthorized
  File "/usr/local/lib/python3.2/dist-packages/falcon/__init__.py", line 32, in <module>
    from falcon.api import API, DEFAULT_MEDIA_TYPE  # NOQA
  File "/usr/local/lib/python3.2/dist-packages/falcon/api.py", line 22, in <module>
    from falcon.request import Request, RequestOptions
  File "/usr/local/lib/python3.2/dist-packages/falcon/request.py", line 38
    DEFAULT_ERROR_LOG_FORMAT = (u'{0:%Y-%m-%d %H:%M:%S} [FALCON] [ERROR]'
                                                                        ^
SyntaxError: invalid syntax
```

It also happened when I directly import in a Python file.

**Comment by fbukevin** [comment]
Oh, I found my Python version is too old, and `u''` syntax seems only support for version >= 3.3. This answer helps: [http://stackoverflow.com/questions/34244990/syntax-error-when-running-falcon-framework-tutorial-with-gunicorn](http://stackoverflow.com/questions/34244990/syntax-error-when-running-falcon-framework-tutorial-with-gunicorn)
