### ISSUE TITLE
Example "on_startup.py" not working, decorator missing

### ISSUE THREAD

**Issue by burgerdev** [timothycrosley/hug#203]
```
$ git clone https://github.com/timothycrosley/hug
$ hug -f hug/examples/on_startup.py
Traceback (most recent call last):
  File "~/.local/bin/hug", line 9, in <module>
    load_entry_point('hug==1.9.9', 'console_scripts', 'hug')()
  File "hug/run.py", line 171, in hug.run.terminal (hug/run.c:4431)
  File "<frozen importlib._bootstrap_external>", line 385, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 806, in load_module
  File "<frozen importlib._bootstrap_external>", line 665, in load_module
  File "<frozen importlib._bootstrap>", line 268, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 662, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "on_startup.py", line 8, in <module>
    @hug.startup()
AttributeError: module 'hug' has no attribute 'startup'
```

**Comment by burgerdev** [comment]
Nevermind, just saw it was introduced after 1.9.9 release.
