### ISSUE TITLE
How to use Class based routing

### ISSUE THREAD

**Issue by SkiftCreative** [timothycrosley/hug#213]
After reading up on #162 

I am curious how I would use this, along with further routing.

so if I have the class from the above:
```
class class_1:
    pass
````

how would I route the HTTP verbs to given methods. Ideally, I would like to do something like:
```
class User:
    @hug.get('/')
    def get(self):
        return {[...], [...]}

    @hug.get('/{id}')
    def get_by_id(self, id: int):
        return {...}
```

which means that `get_by_id()` method would route to `/user/{id}' if I mounted the class per above:

```
import hug
import library

route = hug.route.API(__name__)
route.object('/user')(library.User)
```

One purpose for this is that I would like to use something like the `remodel` module for interacting with rethinkdb, and it requires setting up your models/resources/documents based on classes which inherit from its own `Model` class. So I am trying to see if there is a way I can get them to play together nicely without having to write my own wrapper either around, or to replace remodel.

The other option would be to do the normal method based routing, but then have a class next to them that is the actual DB model. The methods then interact with that class. But seeing some issues like #211 makes me think that would go against the grain with getting auto generated docs would work.

**Comment by timothycrosley** [comment]
Hi @SkiftCreative,

With object based routing you can do the following:

    class User:
        @hug.object.get('/')
        def get(self):
            return {[...], [...]}

        @hug.object.get('/{id}')
        def get_by_id(self, id: int):
            return {...}

and your mounting code below is correct and should would work unchanged.

I hope this is helpful!

Thanks!

~Timothy

**Comment by SkiftCreative** [comment]
Awesome to know. thanks.

**Comment by SkiftCreative** [comment]
So im trying this, on python 3.5 

```
import hug
from remodel.models import Model


class Foo(Model):

    @hug.object.get('/')
    def get_list(self):
        """get the latest post."""
        return [
            {"title": "awesome", "content": "that is great"},
            {"title": "sweet", "content": "that is also great"}
        ]


route = hug.route.API(__name__)
route.object('/posts')(Foo)
```

and when I run `hug -f api.py` I get this error:

```
> hug -f api.py
Traceback (most recent call last):
  File "/Users/shawn/www/projects/skift/hugtest/env/bin/hug", line 11, in <module>
    sys.exit(run.terminal())
  File "/Users/shawn/www/projects/skift/hugtest/env/lib/python3.5/site-packages/hug/run.py", line 171, in terminal
    api = server(importlib.machinery.SourceFileLoader(file_name.split(".")[0], file_name).load_module(),
  File "<frozen importlib._bootstrap_external>", line 385, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 806, in load_module
  File "<frozen importlib._bootstrap_external>", line 665, in load_module
  File "<frozen importlib._bootstrap>", line 268, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 662, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "api.py", line 5, in <module>
    class Foo(Model):
  File "api.py", line 7, in Foo
    @hug.object.get('/')
AttributeError: module 'hug' has no attribute 'object'
```

Looking through the source (from the pypi package installed from pip)

**Comment by timothycrosley** [comment]
Hi @SkiftCreative this is simply because class based routes are a 2.0.0 feature which hasn't been released yet (slated for release March 1st). You can test them out now by installing hug from the develop branch:

     pip install git+git://github.com/timothycrosley/hug.git@develop

**Comment by SkiftCreative** [comment]
Hrmm, still seem to get this error.

```
> hug -f api.py
Traceback (most recent call last):
  File "/Users/shawn/www/projects/skift/hugtest/env/bin/hug", line 9, in <module>
    load_entry_point('hug==1.9.9', 'console_scripts', 'hug')()
  File "/Users/shawn/www/projects/skift/hugtest/env/lib/python3.5/site-packages/hug/run.py", line 183, in terminal
    api_module = importlib.machinery.SourceFileLoader(file_name.split(".")[0], file_name).load_module()
  File "<frozen importlib._bootstrap_external>", line 385, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 806, in load_module
  File "<frozen importlib._bootstrap_external>", line 665, in load_module
  File "<frozen importlib._bootstrap>", line 268, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 662, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "api.py", line 5, in <module>
    class Foo(Model):
  File "api.py", line 7, in Foo
    @hug.object.get('/')
TypeError: get() takes 1 positional argument but 2 were given
```

**Comment by timothycrosley** [comment]
Update it to:
    class User:
        @hug.object.get(urls='/')
        def get(self):
            return {[...], [...]}

        @hug.object.get(urls='/{id}')
        def get_by_id(self, id: int):
            return {...}

And it should work, the class based routing currently does not exactly match the signature of the base decorating methods, though that is something I want to resolve

Thanks!

~Timothy

**Comment by SkiftCreative** [comment]
Ah, well i think i found where it breaks then ;-)

```
import hug
from remodel.models import Model


class Foo(Model):

    @hug.object.get(urls='/')
    def get_list(self):
        """get the latest post."""
        return [
            {"title": "awesome", "content": "that is great"},
            {"title": "sweet", "content": "that is also great"}
        ]


route = hug.route.API(__name__)
route.object('/posts')(Foo)
```

and the response:
```
> hug -f api.py
Traceback (most recent call last):
  File "/Users/shawn/www/projects/skift/hugtest/env/bin/hug", line 9, in <module>
    load_entry_point('hug==1.9.9', 'console_scripts', 'hug')()
  File "/Users/shawn/www/projects/skift/hugtest/env/lib/python3.5/site-packages/hug/run.py", line 183, in terminal
    api_module = importlib.machinery.SourceFileLoader(file_name.split(".")[0], file_name).load_module()
  File "<frozen importlib._bootstrap_external>", line 385, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 806, in load_module
  File "<frozen importlib._bootstrap_external>", line 665, in load_module
  File "<frozen importlib._bootstrap>", line 268, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 662, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "api.py", line 17, in <module>
    route.object('/posts')(Foo)
  File "/Users/shawn/www/projects/skift/hugtest/env/lib/python3.5/site-packages/hug/route.py", line 131, in object
    return Object(*kargs, **kwargs)
TypeError: __init__() takes 1 positional argument but 2 were given
```

Trying to debug it. But I don't see what is passing it the other argument.

**Comment by timothycrosley** [comment]
Hi @SkiftCreative,

It's the same issue of a different function signature, this time in the root object route, ie if you changed `route.object('/posts')(Foo)` to `route.object(urls='/posts')(Foo)` it would work. However, I've updated hug to have the same signature across uses to be more intuitive, so if you update your local installation it should work without modification as should `@hug.object.get('/{id}')`

Thanks!

~Timothy

**Comment by SkiftCreative** [comment]
Awesome. That did the trick. So i guess I will be on the dev branch until 2.0 is released.
