### ISSUE TITLE
Bug - Documentation creation seems to fail when adding output types to the "API signature"

### ISSUE THREAD

**Issue by ErwinHaasnoot** [timothycrosley/hug#218]
Hi again!

I ran into a bug - or a mistake in the way I think about defining apis. I want to add output types to my API signatures, so I can inform users of my API on what to expect in return from the API call. However, it throws an exception when I try to access the documentation. That the outgoing type is not JSON serializable.

I suppose the same special sauce that makes input type signatures work should be applied to output types?

My API
```
import hug

@hug.get('/')
def stuff() -> hug.types.text
    return "hello"
```

Exception:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tornado/web.py", line 1422, in _execute
    result = self.prepare()
  File "/usr/local/lib/python3.5/dist-packages/tornado/web.py", line 2681, in prepare
    self.fallback(self.request)
  File "/usr/local/lib/python3.5/dist-packages/tornado/wsgi.py", line 277, in __call__
    WSGIContainer.environ(request), start_response)
  File "/usr/local/lib/python3.5/dist-packages/falcon/api.py", line 182, in __call__
    responder(req, resp, **params)
  File "/usr/local/lib/python3.5/dist-packages/hug/run.py", line 103, in handle_404
    response.data = json.dumps(to_return, indent=4, separators=(',', ': ')).encode('utf8')
  File "/usr/lib/python3.5/json/__init__.py", line 237, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.5/json/encoder.py", line 201, in encode
    chunks = list(chunks)
  File "/usr/lib/python3.5/json/encoder.py", line 429, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/usr/lib/python3.5/json/encoder.py", line 403, in _iterencode_dict
    yield from chunks
  File "/usr/lib/python3.5/json/encoder.py", line 403, in _iterencode_dict
    yield from chunks
  File "/usr/lib/python3.5/json/encoder.py", line 403, in _iterencode_dict
    yield from chunks
  File "/usr/lib/python3.5/json/encoder.py", line 403, in _iterencode_dict
    yield from chunks
  File "/usr/lib/python3.5/json/encoder.py", line 403, in _iterencode_dict
    yield from chunks
  File "/usr/lib/python3.5/json/encoder.py", line 436, in _iterencode
    o = _default(o)
  File "/usr/lib/python3.5/json/encoder.py", line 180, in default
    raise TypeError(repr(o) + " is not JSON serializable")
```

Thanks again!

Best,

Erwin

**Comment by timothycrosley** [comment]
Hi @ErwinHaasnoot,

This is indeed a bug! Thanks for uncovering it, the behavior you suggested is indeed the desired one and should now once again be supported.

Thanks!

~Timothy

**Comment by ErwinHaasnoot** [comment]
Awesome. Thanks for fixing it so quickly!
