### ISSUE TITLE
How to import modules with undecorated functions?

### ISSUE THREAD

**Issue by michaelbuckner** [timothycrosley/hug#36]
Is there a way to import modules/libraries that are not decorated with @hug? I must be missing something obvious?

Here what I'm getting:
```
C:\Users\mike\PycharmProjects\hugs\person> hug -f .\app.py
Traceback (most recent call last):
  File "C:\Users\mike\AppData\Local\Programs\Python\Python35\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\mike\AppData\Local\Programs\Python\Python35\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\mike\AppData\Local\Programs\Python\Python35\Scripts\hug.exe\__main__.py", line 9, in <module>
  File "C:\Users\mike\AppData\Local\Programs\Python\Python35\lib\site-packages\hug\run.py", line 147, in terminal
    api = server(importlib.machinery.SourceFileLoader(file_name.split(".")[0], file_name).load_module())
  File "<frozen importlib._bootstrap_external>", line 383, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 804, in load_module
  File "<frozen importlib._bootstrap_external>", line 663, in load_module
  File "<frozen importlib._bootstrap>", line 268, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 660, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File ".\app.py", line 2, in <module>
    import person
ImportError: No module named 'person'
```
Thanks!

**Comment by timothycrosley** [comment]
Hi @michaelbuckner,

Hug APIs should work fine with import external modules, as long as their in the current Python PATH. Is Person in the same directory? Does it have the folder have an `__init__.py` file? Is it the root python directory, or do you need to use relative imports to load it?

Thanks! And I hope these questions help you diagnose your problem

Tim

**Comment by michaelbuckner** [comment]
Hi @timothycrosley, thanks for taking the time to help.

Person is in the same directory, I've tried both ``` import Person ``` as well as ```from . import Person ```

I've tried both with and without a \_\_init__.py file, both in the root of the project, as well as in a module.

Here's what I get with a relative import:

```
  File "app.py", line 4, in <module>
    from . import Person
SystemError: Parent module '' not loaded, cannot perform relative import
```

Any ideas?
<img width="372" alt="screen shot 2015-08-16 at 3 04 04 pm" src="https://cloud.githubusercontent.com/assets/2817174/9294870/ff5c16ae-4427-11e5-9854-0bfb7e33e31d.png">

Any ideas?

**Comment by timothycrosley** [comment]
Hi @michaelbuckner,

Sorry for the delay! It looks like there was a bug when using `-f` instead of `-m` that has been fixed here: 

https://github.com/timothycrosley/hug/pull/52

also I added an example in that pull request of a file successfully being imported.

Thanks!

~Timothy

**Comment by timothycrosley** [comment]
Note this is in the just pushed to PyPI 1.2.0 release :)

**Comment by michaelbuckner** [comment]
@timothycrosley Awesome, thanks so much!
