### ISSUE TITLE
async support is incompatible with threads

### ISSUE THREAD

**Issue by vortec** [timothycrosley/hug#364]
A simple app like this:

```
@hug.get('/ping')
async def ping():
    return 'pong'
```

doesn't work with uWSGI and gunicorn threads. It raises this exception once you requested the endpoint via HTTP:

```
[2016-09-02 11:21:04 +0200] [45145] [ERROR] Error handling request /ping
Traceback (most recent call last):
  File "python3.5/site-packages/gunicorn/workers/gthread.py", line 283, in handle
    keepalive = self.handle_request(req, conn)
  File "python3.5/site-packages/gunicorn/workers/gthread.py", line 332, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "python3.5/site-packages/hug/api.py", line 381, in api_auto_instantiate
    return module.__hug_wsgi__(*kargs, **kwargs)
  File "python3.5/site-packages/falcon/api.py", line 189, in __call__
    responder(req, resp, **params)
  File "python3.5/site-packages/hug/interface.py", line 586, in __call__
    self.render_content(self.call_function(**input_parameters), request, response, **kwargs)
  File "python3.5/site-packages/hug/interface.py", line 530, in call_function
    return self.interface(**parameters)
  File "python3.5/site-packages/hug/interface.py", line 112, in __call__
    return asyncio_call(__hug_internal_self._function, *args, **kwargs)
  File "python3.5/site-packages/hug/interface.py", line 51, in asyncio_call
    loop = asyncio.get_event_loop()
  File "/lib/python3.5/asyncio/events.py", line 589, in get_event_loop
    return get_event_loop_policy().get_event_loop()
  File "/lib/python3.5/asyncio/events.py", line 535, in get_event_loop
    % threading.current_thread().name)
RuntimeError: There is no current event loop in thread 'Thread-4'.`
```

Furthermore, if you use `gunicorn --processes=2 --threads=1 --preload`, you get this exception:

```
Traceback (most recent call last):
  File "python3.5/site-packages/gunicorn/workers/sync.py", line 135, in handle
    self.handle_request(listener, req, client, addr)
  File "python3.5/site-packages/gunicorn/workers/sync.py", line 191, in handle_request
    six.reraise(*sys.exc_info())
  File "python3.5/site-packages/gunicorn/six.py", line 625, in reraise
    raise value
  File "python3.5/site-packages/gunicorn/workers/sync.py", line 176, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "python3.5/site-packages/hug/api.py", line 381, in api_auto_instantiate
    return module.__hug_wsgi__(*kargs, **kwargs)
  File "python3.5/site-packages/falcon/api.py", line 189, in __call__
    responder(req, resp, **params)
  File "python3.5/site-packages/hug/interface.py", line 586, in __call__
    self.render_content(self.call_function(**input_parameters), request, response, **kwargs)
  File "python3.5/site-packages/hug/interface.py", line 530, in call_function
    return self.interface(**parameters)
  File "python3.5/site-packages/hug/interface.py", line 112, in __call__
    return asyncio_call(__hug_internal_self._function, *args, **kwargs)
  File "python3.5/site-packages/hug/interface.py", line 53, in asyncio_call
    loop.run_until_complete(function)
  File "/lib/python3.5/asyncio/base_events.py", line 330, in run_until_complete
    self.run_forever()
  File "/lib/python3.5/asyncio/base_events.py", line 301, in run_forever
    self._run_once()
  File "/lib/python3.5/asyncio/base_events.py", line 1162, in _run_once
    event_list = self._selector.select(timeout)
  File "/lib/python3.5/selectors.py", line 560, in select
    kev_list = self._kqueue.control(None, max_ev, timeout)
OSError: [Errno 9] Bad file descriptor
```

**Comment by vortec** [comment]
@rodcloutier , can you help me on this one?

**Comment by timothycrosley** [comment]
This is now fixed in develop and will make its way into the next release

Thanks!

~Timothy
