### ISSUE TITLE
TypeError when parsing JSON with 'self' as a key

### ISSUE THREAD

**Issue by lttviet** [timothycrosley/hug#392]
Hi,

I was testing hug with intercom api and got TypeError because their json contains 'self' key.

For example:

```
@hug.post("/test")
def test(body):
    return body
```

with this request:

```
data = {"self": "localhost"}
requests.post("http://127.0.0.1":8000/test", json=data)

```

will result in:

```
Traceback (most recent call last):
  File "/usr/lib/python3.5/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
  File "/home/lttviet/.local/lib/python3.5/site-packages/falcon/api.py", line 189, in __call__
    responder(req, resp, **params)
  File "/home/lttviet/.local/lib/python3.5/site-packages/hug/interface.py", line 651, in __call__
    self.render_content(self.call_function(**input_parameters), request, response, **kwargs)
TypeError: call_function() got multiple values for argument 'self'
127.0.0.1 - - [19/Oct/2016 18:29:23] "POST /test HTTP/1.1" 500 59
```

**Comment by timothycrosley** [comment]
This is now fixed in development and ready for the next release, thanks!
