### ISSUE TITLE
Route /{url} can't start with a "v"

### ISSUE THREAD

**Issue by banteg** [timothycrosley/hug#418]
You can have any route as long as it doesn't start with a "v" — Henry Ford

```python
import hug

@hug.get('/{url}')
def henry_ford(url):
    return url

api = hug.API(__name__)
hug.test.get(api, '/very-nice')
```

```
Traceback (most recent call last):
  File "x.py", line 8, in <module>
    hug.test.get(api, '/very-nice')
  File "/usr/local/lib/python3.5/dist-packages/hug/test.py", line 49, in call
    response)
  File "/usr/local/lib/python3.5/dist-packages/falcon/api.py", line 189, in __call__
    responder(req, resp, **params)
  File "/usr/local/lib/python3.5/dist-packages/hug/interface.py", line 631, in __call__
    api_version = int(api_version) if api_version is not None else api_version
ValueError: invalid literal for int() with base 10: 'ery-nice'
```

Pull request on its way.

**Comment by timothycrosley** [comment]
Closing this as your fix is now merged in development and ready for the next release.

Thanks!

~Timothy
