### ISSUE TITLE
@hug.type(extend=hug.types.text) returns "__init__() takes 1 positional argument but 2 were given"

### ISSUE THREAD

**Issue by lokeshmeher** [timothycrosley/hug#432]
I have an endpoint:
```python
@hug.type(extend=hug.types.text)
def valid_survey_id(val):
    """A valid survey_id."""
    if not db.collection.find_one({'survey_id': val}):
        raise ValueError('survey_id ({}) does not exist!'.format(val))

@hug.get('/survey/{survey_id}', output=hug.output_format.pretty_json)
def get_meta(survey_id: valid_survey_id):
    return 'Got valid survey_id: {}'.format(survey_id)
```
I get the error in response:
```json
{
    "errors": {
        "survey_id": "__init__() takes 1 positional argument but 2 were given"
    }
}
```
I even tried with:
```python
@hug.type(extend=hug.types.text)
def valid_survey_id(val):
    """A valid survey_id."""
    pass
```
but got the same error.  
I tried to print all parameters to `hug.types.create()` function:
```python
def create(doc=None, error_text=None, exception_handlers=empty.dict, extend=Type, chain=True):
    """Creates a new type handler with the specified type-casting handler"""
    extend = extend if type(extend) == type else type(extend)
    print('doc:', doc, flush=True)
    print('error_text:', error_text, flush=True)
    print('exception_handlers:', exception_handlers, flush=True)
    print('extent:', extend, flush=True)
    print('chain:', chain, flush=True)
    # ...
```
but it did not print anything to the console.  
I also tried with subclassing `hug.types.text`:
```python
class ValidSurveyId(hug.types.text):
    """A valid survey_id."""
    def __call__(self, val):
        val = super().__call__(val)
        if not db.collection.find_one({'survey_id': val}):
            raise ValueError('survey_id ({}) does not exist!'.format(val))
        return val  # I also tried with removing this line (as given in the documentation).
```
but it gave a different error (in the console) and the program aborted:
```
TypeError: __init__() takes 1 positional argument but 4 were given
```
I am not sure what is the issue here.  

**Note**: the database collection name and variable names have been changed for security purposes.

**Comment by disarticulate** [comment]
Which is weird because the documentation:

```
import hug
class TheAnswer(hug.types.number):
    """My new documentation"""

    def __call__(self, value):
        value = super().__call__(value)
        if value != 42:
            raise ValueError('Value is not the answer to everything.')
```

Clearly indicates you should be able to extend the types. But the same error type is:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: __init__() takes 1 positional argument but 4 were given
```

using:
```
Python 3.5.2 (default, Nov 17 2016, 22:46:45) 
[GCC 5.3.0] on linux
hug.version.__version__
'1.0.0'
server_1   | Traceback (most recent call last):
server_1   |   File "/usr/local/bin/hug", line 9, in <module>
server_1   |     load_entry_point('hug==2.2.0', 'console_scripts', 'hug')()
server_1   |   File "/usr/local/lib/python3.5/site-packages/hug/interface.py", line 463, in __call__
server_1   |     result = self.interface(**pass_to_function)
server_1   |   File "/usr/local/lib/python3.5/site-packages/hug/interface.py", line 117, in __call__
server_1   |     return __hug_internal_self._function(*args, **kwargs)
server_1   |   File "/usr/local/lib/python3.5/site-packages/hug/development_runner.py", line 45, in hug
server_1   |     api_module = importlib.machinery.SourceFileLoader(file.split(".")[0], file).load_module()
server_1   |   File "<frozen importlib._bootstrap_external>", line 388, in _check_name_wrapper
server_1   |   File "<frozen importlib._bootstrap_external>", line 809, in load_module
server_1   |   File "<frozen importlib._bootstrap_external>", line 668, in load_module
server_1   |   File "<frozen importlib._bootstrap>", line 268, in _load_module_shim
server_1   |   File "<frozen importlib._bootstrap>", line 693, in _load
server_1   |   File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
server_1   |   File "<frozen importlib._bootstrap_external>", line 665, in exec_module
server_1   |   File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
server_1   |   File "server.py", line 2, in <module>
server_1   |     from handlers import points, geohash
server_1   |   File "/app/handlers/geohash.py", line 8, in <module>
server_1   |     class Lat(hug.types.number):
server_1   | TypeError: __init__() takes 1 positional argument but 4 were given
```

**Comment by cag** [comment]
I agree that this is weird. The decorator doesn't do what you may expect. The decorator actually turns the function into the type for a callable object. See the following:

```python
@hug.type(extend=hug.types.text)
def valid_survey_id(val):
    """A valid survey_id."""
    return val

@hug.get('/foo/{survey_id}', output=hug.output_format.pretty_json)
def get_meta(survey_id: valid_survey_id()): # <-- notice the extra call
    return 'Got valid survey_id: {}'.format(survey_id)
```

**Comment by lokeshmeher** [comment]
@cag I went with a simple function. Just copy-pasted the implementation in source code and added my own custom validations to it.

**Comment by timothycrosley** [comment]
Going to go ahead and mark this as a bug as the implementation should not require having to instantiate the object yourself, as it feels clumsy and is confusing. This will be fixed before the next release.

Thanks!

~Timothy

**Comment by timothycrosley** [comment]
This is now fixed in develop and will make its way into the next release.

Thanks!

~Timothy
