### ISSUE TITLE
Streaming data?

### ISSUE THREAD

**Issue by Pusnow** [timothycrosley/hug#443]
Is it possible to stream some text data from generator?

[falcon example](http://andrewbunday.co.uk/2016/05/25/streaming-responses-with-falcon/)
[flask example](http://flask.pocoo.org/docs/0.12/patterns/streaming/)

**Comment by Pusnow** [comment]
I solved this issue by code below

```
@hug.format.content_type('text/csv; charset=utf-8')
def format_as_csv_stream(data, request=None, response=None):
    now = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
    response.append_header('Content-Disposition',
                           ('attachment; filename="Download %s.csv"' % now))
    response.stream = data


@hug.post("/test", output=format_as_csv_stream)
def csv_test():

    return some_data_stream
```

**Comment by dazzag24** [comment]
Does anyone have a working example of this working.  I can't make the above work.

`Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 313, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 341, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/usr/lib/python3.5/wsgiref/simple_server.py", line 138, in handle
    handler.run(self.server.get_app())
  File "/usr/lib/python3.5/wsgiref/handlers.py", line 144, in run
    self.close()
  File "/usr/lib/python3.5/wsgiref/simple_server.py", line 36, in close
    self.status.split(' ',1)[0], self.bytes_sent
AttributeError: 'NoneType' object has no attribute 'split'
`
I'd also be happy to see an example of non streaming return of CSV data.
Thanks
