### ISSUE TITLE
server error if client posts bad json

### ISSUE THREAD

**Issue by bernhardreiter** [timothycrosley/hug#457]
```sh
hug -f examples/post_body_example.py -p 7000
```

```python
import requests
requests.post('http://localhost:7000/post_here', data='not json}', headers={'content-type':'application/json'})
```

results into a 500 server error and there is no easy (documented) way to do the parsing yourself.

This is with hug 2.2.0, full traceback
```
127.0.0.1 - - [17/Feb/2017 16:06:38] "POST /post_here HTTP/1.1" 200 11
Traceback (most recent call last):
  File "/usr/lib/python3.4/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
  File "/home/fody/.local/lib/python3.4/site-packages/falcon/api.py", line 189, in __call__
    responder(req, resp, **params)
  File "/home/fody/.local/lib/python3.4/site-packages/hug/interface.py", line 646, in __call__
    input_parameters = self.gather_parameters(request, response, api_version, **kwargs)
  File "/home/fody/.local/lib/python3.4/site-packages/hug/interface.py", line 507, in gather_parameters
    body = body_formatter(body, **content_params)
  File "/home/fody/.local/lib/python3.4/site-packages/hug/input_format.py", line 43, in json
    return json_converter.loads(text(body, charset=charset))
  File "/usr/lib/python3.4/json/__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.4/json/decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.4/json/decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 1 column 1 (char 0)
```

**Comment by bernhardreiter** [comment]
It does not seem to be possible to parse the body with somebodies own code like this:
```python
@hug.post('/post_here',  body_parse=False)
def post_here(request):
  print(request.stream._bytes_remaining)
  raw_body = request.stream.read()
```

because some other code part seem to have consumed the stream contents already.
