### ISSUE TITLE
Serializing datetime.timedelta

### ISSUE THREAD

**Issue by dmth** [timothycrosley/hug#468]
Hi,

I just ran into the problem of serializing `datetime.timedelta` objects.

One way to solve this, is to add: 
```python
    if isinstance(item, timedelta):
        return item.total_seconds()
```
and an import of `timedelta` to the json_converter in `output_format.py`.

This approach serializes the timedelta to seconds (+/-) .

Do you think this is a reasonable solution? 

In case someone is interested of the stacktrace (or just to feed search-engines):
```
Traceback (most recent call last):
  File "/usr/lib/python3.4/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
  File "/usr/local/lib/python3.4/dist-packages/falcon/api.py", line 189, in __call__
    responder(req, resp, **params)
  File "/usr/local/lib/python3.4/dist-packages/hug/interface.py", line 651, in __call__
    self.render_content(self.call_function(**input_parameters), request, response, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/hug/interface.py", line 606, in render_content
    content = self.outputs(content, **self._arguments(self._params_for_outputs, request, response))
  File "/usr/local/lib/python3.4/dist-packages/hug/output_format.py", line 96, in json
    return json_converter.dumps(content, default=_json_converter, **kwargs).encode('utf8')
  File "/usr/lib/python3.4/json/__init__.py", line 237, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.4/json/encoder.py", line 192, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.4/json/encoder.py", line 250, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.4/dist-packages/hug/output_format.py", line 73, in _json_converter
    raise TypeError("Type not serializable")
TypeError: Type not serializable
```

**Comment by timothycrosley** [comment]
Thanks for reporting!
Closing as this is now supported in the development branch.

Thanks!

~Timothy
