### ISSUE TITLE
Attempted serialization of non-JSON return type

### ISSUE THREAD

**Issue by NoMotion** [timothycrosley/hug#516]
My issue looks identical to #218. My code is small and straightforward:
```
@hug.post('/api/commands', output=hug.output_format.html)
@hug.get('/api/commands', output=hug.output_format.html)
def nagiosCommandHelp(**kwargs):
    """
    Returns command help document when no command is specified
    """
    with open(path.join(cwd, "commands_help.html")) as helpfile:
        return helpfile.read()
```
However I am using newest version 2.3.0 and am experiencing a very similar traceback to #218 :
```
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
  File "/usr/local/lib/python3.5/site-packages/falcon/api.py", line 227, in __call__
    responder(req, resp, **params)
  File "/usr/local/lib/python3.5/site-packages/hug/api.py", line 291, in handle_404
    response.data = json.dumps(to_return, indent=4, separators=(',', ': ')).encode('utf8')
  File "/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/__init__.py", line 237, in dumps
    **kw).encode(obj)
  File "/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/encoder.py", line 200, in encode
    chunks = list(chunks)
  File "/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/encoder.py", line 429, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/encoder.py", line 403, in _iterencode_dict
    yield from chunks
  File "/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/encoder.py", line 403, in _iterencode_dict
    yield from chunks
  File "/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/encoder.py", line 403, in _iterencode_dict
    yield from chunks
  File "/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/encoder.py", line 403, in _iterencode_dict
    yield from chunks
  File "/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/encoder.py", line 403, in _iterencode_dict
    yield from chunks
  File "/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/encoder.py", line 403, in _iterencode_dict
    yield from chunks
  File "/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/encoder.py", line 403, in _iterencode_dict
    yield from chunks
  File "/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/encoder.py", line 436, in _iterencode
    o = _default(o)
  File "/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/encoder.py", line 179, in default
    raise TypeError(repr(o) + " is not JSON serializable")
```
I don't know if these issues are related but any advice on troubleshooting what is happening here? I am explicitly returning html to an output type of html, I do not know why json is coming into the mix

**Comment by spartakos87** [comment]
I have the same problem ...any idea how to solve it?

**Comment by timothycrosley** [comment]
Hi @NoMotion,

Thanks for reporting this issue! Unfortunately, I think something must be missing in this report, as despite my best efforts I have been unable to reproduce - I've added additional tests to verify that the issue described here does not occur with the simple API it is suggested causes it here: https://github.com/timothycrosley/hug/pull/532/files

If you or @spartakos87 have any additional information, or are able to provide a failing test I will reopen and fix ASAP.

Thanks!

~Timothy

**Comment by NoMotion** [comment]
@timothycrosley 
Finally got to looking at this. **Problem was I did not have a favicon.** This created a 404 and ran the hug handler to return documentation page which I had not configured
