### ISSUE TITLE
Auto-reload fails when using the -m flag

### ISSUE THREAD

**Issue by mac-chaffee** [timothycrosley/hug#574]
I'm using the development server to serve a module using the -m flag.

Whenever I change a file, the server tries to auto-reload, but always fails with this exception:

```
> Reloading due to file change: /home/mac/meps-metrics/backend/api/meps_data.py
Traceback (most recent call last):
  File "/home/mac/meps-metrics/backend/venv/lib/python3.6/site-packages/hug/development_runner.py", line 83, in hug
    _start_api(api_module, port, no_404_documentation, not ran)
  File "/home/mac/meps-metrics/backend/venv/lib/python3.6/site-packages/hug/development_runner.py", line 42, in _start_api
    API(api_module).http.serve(port, no_404_documentation, show_intro)
  File "/home/mac/meps-metrics/backend/venv/lib/python3.6/site-packages/hug/api.py", line 262, in serve
    httpd.serve_forever()
  File "/usr/local/lib/python3.6/socketserver.py", line 236, in serve_forever
    ready = selector.select(poll_interval)
  File "/usr/local/lib/python3.6/selectors.py", line 376, in select
    fd_event_list = self._poll.poll(timeout)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mac/meps-metrics/backend/venv/bin/hug", line 11, in <module>
    sys.exit(development_runner.hug.interface.cli())
  File "/home/mac/meps-metrics/backend/venv/lib/python3.6/site-packages/hug/interface.py", line 485, in __call__
    result = self.interface(**pass_to_function)
  File "/home/mac/meps-metrics/backend/venv/lib/python3.6/site-packages/hug/interface.py", line 99, in __call__
    return __hug_internal_self._function(*args, **kwargs)
  File "/home/mac/meps-metrics/backend/venv/lib/python3.6/site-packages/hug/development_runner.py", line 95, in hug
    api_module = importlib.import_module(module)
  File "/home/mac/meps-metrics/backend/venv/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named '_virtualenv_distutils'
```

Python info:
```
Python 3.6.3 (default, Oct 15 2017, 15:26:49) 
[GCC 5.4.0 20160609] on linux
```

My code is here if it helps:
https://gitlab.com/mac-chaffee/meps-metrics/tree/develop/backend

When I run the hug dev server, I use this command: `hug -m api`

**Comment by mac-chaffee** [comment]
Temporary workaround:

Running gunicorn with the --reload flag seems to work

```
gunicorn --reload --bind=0.0.0.0:8000 api.__init__:__hug_wsgi__
```

**Comment by mac-chaffee** [comment]
Hmm so it turns out I can no longer replicate my own bug report! I think we can chalk this one up to user-error and close the issue.

**Comment by velapartners** [comment]
I have been running into a similar issue on Windows 10. Any ideas? Can't seem to figure this out.

--
  File "c:\users\me\anaconda3\envs\dlnd\lib\site-packages\hug\development_runner.py", line 84, in hug
    _start_api(api_module, host, port, no_404_documentation, False if silent else not ran)
  File "c:\users\me\anaconda3\envs\dlnd\lib\site-packages\hug\development_runner.py", line 42, in _start_api
    API(api_module).http.serve(host, port, no_404_documentation, show_intro)
  File "c:\users\me\anaconda3\envs\dlnd\lib\site-packages\hug\api.py", line 260, in serve
    httpd.serve_forever()
