### ISSUE TITLE
POST endpoint clarification

### ISSUE THREAD

**Issue by srijiths** [timothycrosley/hug#688]
Hi All,

I have a sample POST endpoint like below.

```
api = hug.API(__name__)

@hug.default_input_format("application/json")
@hug.post('/find_best_params', versions=1)
def find_best_params(body):
  print("Body :", body.read().decode('utf-8'))

if __name__ == '__main__':
    api.http.serve()
```
I am getting below exception when i send a request.

```
Body : {"body":{"data":{"train_file":"","delimiter":"","qualifier":""},"algo_params":{"param_grid":{"n_epochs":[5,10],"lr_all":[0.002,0.005],"reg_all":[0.4,0.6]},"algo_class":"SVD"},"search_params":{"search_algo":"GridSearch","cv":10,"refit":true,"return_train_measures":true}}}
Traceback (most recent call last):
  File "/usr/lib/python3.5/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
  File "/usr/local/lib/python3.5/dist-packages/falcon/api.py", line 244, in __call__
    responder(req, resp, **params)
  File "/home/ubuntu/srijith/dl/lib/python3.5/site-packages/hug/api.py", line 320, in version_router
    **kwargs)
  File "/home/ubuntu/srijith/dl/lib/python3.5/site-packages/hug/interface.py", line 793, in __call__
    raise exception
  File "/home/ubuntu/srijith/dl/lib/python3.5/site-packages/hug/interface.py", line 766, in __call__
    self.render_content(self.call_function(input_parameters), context, request, response, **kwargs)
  File "/home/ubuntu/srijith/dl/lib/python3.5/site-packages/hug/interface.py", line 703, in call_function
    return self.interface(**parameters)
  File "/home/ubuntu/srijith/dl/lib/python3.5/site-packages/hug/interface.py", line 100, in __call__
    return __hug_internal_self._function(*args, **kwargs)
  File "recommender.py", line 56, in find_best_params
    print("Body :", body.read().decode('utf-8'))
AttributeError: 'NoneType' object has no attribute 'read'
```
First time  print("Body :", body.read().decode('utf-8')) statement executed correctly and i got the body printed. But why again its getting called  and getting in to an exception ?

Thank You

**Comment by srijiths** [comment]
I have done it in a different way and issue solved.

```
@hug.post('/find_best_params', versions=1)
def find_best_params(response, body=None):
    if body is not None:
        # YOUR LOGIC
```
And i have omitted explicit starting of the server also.
```
api = hug.API(__name__)
if __name__ == '__main__':
    api.http.serve()
```

Not sure whether this is the correct solution
