### ISSUE TITLE
Combining multiple API files fails, when no directives are defined

### ISSUE THREAD

**Issue by timothycrosley** [timothycrosley/hug#70]
If the example for splitting APIs across multiple files is followed an error occurs when no directives are defined, due to incorrect default in the code:

    (testhug) william@Williams-MBP:~/projects/testhug/multi$ hug -f __init__.py
    Traceback (most recent call last):
    File "/Users/william/projects/testhug/bin/hug", line 11, in <module>
        sys.exit(run.terminal())
    File "/Users/william/projects/testhug/lib/python3.4/site-packages/hug/run.py", line 171, in terminal
        api = server(importlib.machinery.SourceFileLoader(file_name.split(".")[0], file_name).load_module(),
    File "<frozen importlib._bootstrap>", line 539, in _check_name_wrapper
    File "<frozen importlib._bootstrap>", line 1614, in load_module
    File "<frozen importlib._bootstrap>", line 596, in _load_module_shim
    File "<frozen importlib._bootstrap>", line 1220, in load
    File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
    File "<frozen importlib._bootstrap>", line 1129, in _exec
    File "<frozen importlib._bootstrap>", line 1471, in exec_module
    File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
    File "__init__.py", line 10, in <module>
        @hug.extend_api('/thing')
    File "/Users/william/projects/testhug/lib/python3.4/site-packages/hug/decorators.py", line 194, in decorator
        module.__hug__.extend(api, route)
    File "/Users/william/projects/testhug/lib/python3.4/site-packages/hug/decorators.py", line 97, in extend
        for directive in getattr(module.__hug__, '_directives', ()).values():
    AttributeError: 'tuple' object has no attribute ‘values’

This needs to be fixed ASAP and prior to the next release. A test should be added to guarantee this wont happen again.

**Comment by timothycrosley** [comment]
Fixed in version 1.4.0
