### ISSUE TITLE
Parse error on CORS Middleware in hug.extend

### ISSUE THREAD

**Issue by JGabrielGruber** [timothycrosley/hug#764]
I love hug and all, but, there is a problem with the CORS middleware; if you're using **hug.extend**, like in this code:

````
# teste.py
import	hug

import extended

api = hug.API(__name__)
api.http.add_middleware(hug.middleware.CORSMiddleware(api, allow_origins=["*"]))

@hug.extend_api('/extended')
def empresa_api():
	return [extended]
````
````
# extended.py
import	hug

@hug.get('/{id}')
def test(id):
	return "Testing " + id
````
It generates this beautiful **error**, if you make a **OPTIONS** request in **/extended/12**:
```
Traceback (most recent call last):
  File "/directory/lib/python3.7/sre_parse.py", line 1021, in parse_template
    this = chr(ESCAPES[this][1])
KeyError: '\\w'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.7/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
  File "/directory/lib/python3.7/site-packages/falcon/api.py", line 260, in __call__
    process_response(req, resp, resource, req_succeeded)
  File "/directory/lib/python3.7/site-packages/falcon/api_helpers.py", line 93, in shim
    process_response(req, resp, resource)
  File "/directory/lib/python3.7/site-packages/hug/middleware.py", line 147, in process_response
    for _, routes in self.api.http.routes.items()
  File "/directory/lib/python3.7/site-packages/hug/middleware.py", line 148, in <genexpr>
    for method, _ in routes[self.match_route(request.path)].items()
  File "/directory/lib/python3.7/site-packages/hug/middleware.py", line 131, in match_route
    if re.match(re.sub(r'/{[^{}]+}', '/[\w-]+', route) + '$', reqpath):
  File "/directory/lib/python3.7/re.py", line 192, in sub
    return _compile(pattern, flags).sub(repl, string, count)
  File "/directory/lib/python3.7/re.py", line 309, in _subx
    template = _compile_repl(template, pattern)
  File "/directory/lib/python3.7/re.py", line 300, in _compile_repl
    return sre_parse.parse_template(repl, pattern)
  File "/directory/lib/python3.7/sre_parse.py", line 1024, in parse_template
    raise s.error('bad escape %s' % this, len(this))
re.error: bad escape \w at position 2
127.0.0.1 - - [05/Apr/2019 21:46:55] "OPTIONS /extended/1 HTTP/1.1" 500 59
```
I made a temporary fix for this in my use case, but, it's not right:
```
class CORSMiddleware(object):
	"""A middleware for allowing cross-origin request sharing (CORS)

	Adds appropriate Access-Control-* headers to the HTTP responses returned from the hug API,
	especially for HTTP OPTIONS responses used in CORS preflighting.
	"""
	__slots__ = ('api', 'allow_origins', 'allow_credentials', 'max_age')

	def __init__(self, api, allow_origins: list=['*'], allow_credentials: bool=True, max_age: int=None):
		self.api = api
		self.allow_origins = allow_origins
		self.allow_credentials = allow_credentials
		self.max_age = max_age

	def process_response(self, request, response, resource):
		"""Add CORS headers to the response"""
		response.set_header('Access-Control-Allow-Credentials', str(self.allow_credentials).lower())

		origin = request.get_header('ORIGIN')
		if origin and (origin in self.allow_origins) or ('*' in self.allow_origins):
			response.set_header('Access-Control-Allow-Origin', origin)

		if request.method == 'OPTIONS': # check if we are handling a preflight request
			#allowed_methods = set(
			#	method
			#	for _, routes in self.api.http.routes.items()
			#	for method, _ in routes[self.match_route(request.path)].items()
			#)
			#allowed_methods.add('OPTIONS')

			# return allowed methods
			response.set_header('Access-Control-Allow-Methods', 'POST, GET, OPTIONS, PUT, DELETE')
			#response.set_header('Allow', ', '.join(allowed_methods))

			# get all requested headers and echo them back
			requested_headers = request.get_header('Access-Control-Request-Headers')
			response.set_header('Access-Control-Allow-Headers', requested_headers or '')

			# return valid caching time
			if self.max_age:
				response.set_header('Access-Control-Max-Age', self.max_age)
```
Sorry if I made something wrong....

**Comment by timothycrosley** [comment]
Hi @JGabrielGruber,

Thank you for reporting this issue! I have tried locally and have been unable to reproduce.
My steps where:

1. Copying the code giving into a new test_api directory
2. Running the latest version of hug against the teste.py file `hug -f teste.py`
3. Making an OPTIONS request against /extended/12: `http OPTIONS localhost:8000/extended/12`

I received the following response from the client:
```
timothy@timothy-Desktop:~/.config$ http OPTIONS localhost:8000/extended/12
HTTP/1.0 200 OK
Date: Sun, 07 Apr 2019 16:52:03 GMT
Server: WSGIServer/0.2 CPython/3.7.1
access-control-allow-credentials: true
access-control-allow-headers: 
access-control-allow-methods: OPTIONS, GET
access-control-allow-origin: None
allow: OPTIONS, GET
content-length: 0
content-type: application/json; charset=UTF-8
```
And the following log from the server:
```
127.0.0.1 - - [07/Apr/2019 09:52:03] "OPTIONS /extended/12 HTTP/1.1" 200 0
```

To help me reproduce this issue can you confirm:
1. I am calling the right endpoint (/extended/12) using the right method (OPTIONS) ?
2. What version of hug you are using (`hug -v`)
3. What operating system you are running hug on.


Thanks!

~Timothy

**Comment by JGabrielGruber** [comment]
Hi @timothycrosley 
Thank you for replying,
**1** - Yes!
**2** - hug 2.4.1
**3** - 

> Manjaro Linux
> DISTRIB_ID=ManjaroLinux
> DISTRIB_RELEASE=18.0.4
> DISTRIB_CODENAME=Illyria
> DISTRIB_DESCRIPTION="Manjaro Linux"
>

**Comment by timothycrosley** [comment]
Hi @JGabrielGruber,

Thanks for the information! Would you be willing to try the latest release (2.4.8) and see if it fixes this issue for you?

Thanks!

~Timothy

**Comment by JGabrielGruber** [comment]
Hi, @timothycrosley!
Really sorry about that, yep, solved the problem, sorry about this, I didn't know about **pip --upgrade** aushausa.
Thank you very much.
Have a great day!

**Comment by timothycrosley** [comment]
No worries! Just glad to hear that it's working for you now! :)
