### ISSUE TITLE
Whitespace in path

### ISSUE THREAD

**Issue by mdroidian** [timothycrosley/hug#872]
I don't have much python knowledge, but this looks kinda like a whitespace handling in paths.

Has anyone come across something like this before?

```
Traceback (most recent call last):
  File "C:\Users\Uncle Awesome\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Uncle Awesome\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Uncle Awesome\AppData\Roaming\Python\Python38\site-packages\hug\__main__.py", line 3, in <module>
    hug.development_runner.hug.interface.cli()
  File "C:\Users\Uncle Awesome\AppData\Roaming\Python\Python38\site-packages\hug\interface.py", line 650, in __call__
    raise exception
  File "C:\Users\Uncle Awesome\AppData\Roaming\Python\Python38\site-packages\hug\interface.py", line 646, in __call__
    result = self.output(self.interface(**pass_to_function), context)
  File "C:\Users\Uncle Awesome\AppData\Roaming\Python\Python38\site-packages\hug\interface.py", line 129, in __call__
    return __hug_internal_self._function(*args, **kwargs)
  File "C:\Users\Uncle Awesome\AppData\Roaming\Python\Python38\site-packages\hug\development_runner.py", line 65, in hug
    api_module = importlib.machinery.SourceFileLoader(file.split(".")[0], file).load_module()
  File "<frozen importlib._bootstrap_external>", line 462, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 962, in load_module
  File "<frozen importlib._bootstrap_external>", line 787, in load_module
  File "<frozen importlib._bootstrap>", line 265, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 702, in _load
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 779, in exec_module
  File "<frozen importlib._bootstrap_external>", line 915, in get_code
  File "<frozen importlib._bootstrap_external>", line 972, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Uncle'
```

Windows 10
Python 3.8.5
hug 2.6.1

**Comment by mdroidian** [comment]
Can confirm whitespace issue.

I added `file = "C:\path to\file\file.py"` to ln 58 of hug/development_runner.py and it fixed the issue

Looks like it's defined in hug/output_format.py @ ln 311

And maybe this is the issue

```
    elif os.path.isfile(data):
        name, data = data, open(data, "rb")
```

**Comment by mdroidian** [comment]
Well I'm not really sure now.  I tried throwing `print` and `logging.debug` all around the function but nothing came back.
And `data` was always `NameError: name 'data' is not defined`
So I don't how / where to trace or interrupt the code to find the values of the parameters of `file`
I'll be back later to keep trying.

Note to self:  remember [pathlib](https://medium.com/@ageitgey/python-3-quick-tip-the-easy-way-to-deal-with-file-paths-on-windows-mac-and-linux-11a072b58d5f) and [subprocess](https://stackoverflow.com/questions/204017/how-do-i-execute-a-program-from-python-os-system-fails-due-to-spaces-in-path?rq=1)

**Comment by mdroidian** [comment]
Looks like the issue was with an `os.execvpe` call handling whitespace prior to hug
